### ISSUE TITLE
Error setting up entry for pioneer_async - VSX-2021

### ISSUE THREAD

**Issue by Toets** [crowbarz/ha-pioneer_async#5]
Hi, Cool stuff! Unfortunately I fail to properly configure my VSX-2021. I installed ha-pioneer async repo via HACS and was able to add and install via Integrations menu  but at the end shows a "Failed to setup" integration tile.

I am able to successfully implement the original Pioneer integration (but would like to replace due to instability issues)

A telnet session to my AVR shows:
user@system ~]$ telnet 10.100.15.22 8102
Trying 10.100.15.22...
Connected to 10.100.15.22.
Escape character is '^]'.
PWR1
PWR1
PWR1

I wonder if there is some sort of incompatibility issue with this specific model.

Error setting up entry 10.100.15.22:8102 for pioneer_async

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/pioneer_async/__init__.py", line 80, in async_setup_entry
    await pioneer.connect()
  File "/usr/local/lib/python3.8/site-packages/aiopioneer/pioneer_avr.py", line 253, in connect
    reader, writer = await asyncio.wait_for(  # pylint: disable=unused-variable
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.100.15.22', 8102)

**Comment by crowbarz** [comment]
Hi, are you trying to install this integration whilst other API users (eg. the original Pioneer AVR HA integration, iControl5, etc.) is connected to the same port at the same time? With my own AVR, it doesn't like more than 3 or 4 simultaneous API connections, and your AVR model may support even fewer.

You could also try connecting via port 23 instead of 8102.

Another workaround, for some AVRs, is to set up additional ports, on mine the option can be configured at: http://avr/1000/port_number.asp

Nonetheless, the code should probably fail a bit more gracefully on connection refused. I'll update it to catch OSError as well. Thanks for reporting.

**Comment by crowbarz** [comment]
Fixed by 0.6.
