### ISSUE TITLE
Unable to connect to an SC-57

### ISSUE THREAD

**Issue by acato** [crowbarz/ha-pioneer_async#8]
Not sure what’s wrong.
I installed through HACS and can see the integration in the flow. The setup queries for the name, address and port. Once provided, it fails after a while with a “fail to set up error” 

Log try:

Logger: aiohttp.server
Source: custom_components/pioneer_async/config_flow.py:125 
Integration: Pioneer AVR ([documentation](https://github.com/crowbarz/ha-pioneer_async)) 
First occurred: June 4, 2022, 11:32:58 PM (1 occurrences) 
Last logged: June 4, 2022, 11:32:58 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 243, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/pioneer_async/config_flow.py", line 125, in async_step_init
    pioneer = self.hass.data[DOMAIN][entry.entry_id]
KeyError: 'f12187e9456b5754c7ca934fe6737fcb'

**Comment by acato** [comment]
Resolved serendipitously. The issue was that there was the Pioneer app open that was connected to the receiver and was causing any other device trying to connect to fail. You may want to add this check in the documentation.
